"""Initial migration

Revision ID: fc892e329aea
Revises: 
Create Date: 2026-09-06 18:40:40.749397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc892e329aea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('vehicle_class', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_class'), 'vehicles', ['vehicle_class'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=True)
    op.create_table('inference_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('vehicle_class', sa.String(), nullable=False),
    sa.Column('timestep_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_runs_created_at'), 'inference_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_runs_id'), 'inference_runs', ['id'], unique=False)
    op.create_index(op.f('ix_inference_runs_status'), 'inference_runs', ['status'], unique=False)
    op.create_index(op.f('ix_inference_runs_vehicle_id'), 'inference_runs', ['vehicle_id'], unique=False)
    op.create_table('agent_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inference_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_status', sa.String(), nullable=True),
    sa.Column('agent_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inference_id'], ['inference_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_results_agent_name'), 'agent_results', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_results_id'), 'agent_results', ['id'], unique=False)
    op.create_index(op.f('ix_agent_results_inference_id'), 'agent_results', ['inference_id'], unique=False)
    op.create_table('fleet_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inference_id', sa.Integer(), nullable=False),
    sa.Column('readiness_status', sa.String(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('attention_count', sa.Integer(), nullable=False),
    sa.Column('not_ready_count', sa.Integer(), nullable=False),
    sa.Column('unknown_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inference_id'], ['inference_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_readiness_id'), 'fleet_readiness', ['id'], unique=False)
    op.create_index(op.f('ix_fleet_readiness_inference_id'), 'fleet_readiness', ['inference_id'], unique=False)
    op.create_table('inference_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inference_id', sa.Integer(), nullable=False),
    sa.Column('rf_result', sa.JSON(), nullable=True),
    sa.Column('lstm_result', sa.Float(), nullable=True),
    sa.Column('xgb_result', sa.Float(), nullable=True),
    sa.Column('fusion_rul_hours', sa.Float(), nullable=True),
    sa.Column('fusion_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inference_id'], ['inference_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_results_id'), 'inference_results', ['id'], unique=False)
    op.create_index(op.f('ix_inference_results_inference_id'), 'inference_results', ['inference_id'], unique=False)
    op.create_table('telemetry_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inference_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestep', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('telemetry_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inference_id'], ['inference_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_id'), 'telemetry_records', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_inference_id'), 'telemetry_records', ['inference_id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_vehicle_id'), 'telemetry_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_records_vehicle_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_inference_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_id'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_inference_results_inference_id'), table_name='inference_results')
    op.drop_index(op.f('ix_inference_results_id'), table_name='inference_results')
    op.drop_table('inference_results')
    op.drop_index(op.f('ix_fleet_readiness_inference_id'), table_name='fleet_readiness')
    op.drop_index(op.f('ix_fleet_readiness_id'), table_name='fleet_readiness')
    op.drop_table('fleet_readiness')
    op.drop_index(op.f('ix_agent_results_inference_id'), table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_id'), table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_agent_name'), table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index(op.f('ix_inference_runs_vehicle_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_status'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_id'), table_name='inference_runs')
    op.drop_index(op.f('ix_inference_runs_created_at'), table_name='inference_runs')
    op.drop_table('inference_runs')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_class'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
